---
name: Tests

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          package_json_file: NanoKVM-USB/desktop/package.json

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "pnpm"
          cache-dependency-path: NanoKVM-USB/desktop/pnpm-lock.yaml

      - name: Build
        run: |
          cd "NanoKVM-USB/browser/"
          pnpm install
          pnpm build
